--------------------------------------------------------
--  파일이 생성됨 - 토요일-2월-25-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_BOARD
--------------------------------------------------------

  CREATE TABLE T_shopping_board(
	ARTICLENO NUMBER(10,0), 
	ARENTNO NUMBER(10,0) DEFAULT 0, 
	TITLE VARCHAR2(500 BYTE), 
	CONTENT VARCHAR2(4000 BYTE), 
	IMAGEFILENAME VARCHAR2(100 BYTE), 
	WRITEDATE DATE DEFAULT sysdate, 
	ID VARCHAR2(10 BYTE), 
	SORT NUMBER, 
	CNT NUMBER(30,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##SCOTT.T_BOARD
SET DEFINE OFF;
Insert into C##SCOTT.T_BOARD (ARTICLENO,PARENTNO,TITLE,CONTENT,IMAGEFILENAME,WRITEDATE,ID,SORT,CNT) values (7,0,'수정된 제목','수정된 내용','다운로드.jpg',to_date('23/02/09 14:32:04','RR/MM/DD HH24:MI:SS'),'hong',1,14);
Insert into C##SCOTT.T_BOARD (ARTICLENO,PARENTNO,TITLE,CONTENT,IMAGEFILENAME,WRITEDATE,ID,SORT,CNT) values (8,0,'일반테스트','일반테스트','다운로드.jpg',to_date('23/02/09 14:41:49','RR/MM/DD HH24:MI:SS'),'hong',1,1);
Insert into C##SCOTT.T_BOARD (ARTICLENO,PARENTNO,TITLE,CONTENT,IMAGEFILENAME,WRITEDATE,ID,SORT,CNT) values (12,0,'일반글 111','일반글 111111',null,to_date('23/02/20 09:31:59','RR/MM/DD HH24:MI:SS'),'hong',1,0);
Insert into C##SCOTT.T_BOARD (ARTICLENO,PARENTNO,TITLE,CONTENT,IMAGEFILENAME,WRITEDATE,ID,SORT,CNT) values (13,0,'공지글 1111','공지글 1111',null,to_date('23/02/20 09:32:06','RR/MM/DD HH24:MI:SS'),'hong',0,6);
Insert into C##SCOTT.T_BOARD (ARTICLENO,PARENTNO,TITLE,CONTENT,IMAGEFILENAME,WRITEDATE,ID,SORT,CNT) values (1,0,'수정 테스트글입니다','테스트글입니다.',null,to_date('23/02/05 16:28:05','RR/MM/DD HH24:MI:SS'),'hong',0,3);
Insert into C##SCOTT.T_BOARD (ARTICLENO,PARENTNO,TITLE,CONTENT,IMAGEFILENAME,WRITEDATE,ID,SORT,CNT) values (2,0,'안녕하세요','상품후기입니다.',null,to_date('23/02/05 16:28:05','RR/MM/DD HH24:MI:SS'),'hong',0,0);
Insert into C##SCOTT.T_BOARD (ARTICLENO,PARENTNO,TITLE,CONTENT,IMAGEFILENAME,WRITEDATE,ID,SORT,CNT) values (3,2,'답변입니다','상품 후기에 대한 답변입니다.',null,to_date('23/02/05 16:28:05','RR/MM/DD HH24:MI:SS'),'hong',1,0);
Insert into C##SCOTT.T_BOARD (ARTICLENO,PARENTNO,TITLE,CONTENT,IMAGEFILENAME,WRITEDATE,ID,SORT,CNT) values (5,3,'답변입니다','상품 좋습니다.',null,to_date('23/02/05 16:28:05','RR/MM/DD HH24:MI:SS'),'lee',1,0);
Insert into C##SCOTT.T_BOARD (ARTICLENO,PARENTNO,TITLE,CONTENT,IMAGEFILENAME,WRITEDATE,ID,SORT,CNT) values (4,0,'김유신입니다','김유신 테스트글입니다.',null,to_date('23/02/05 16:28:05','RR/MM/DD HH24:MI:SS'),'kim',0,1);
Insert into C##SCOTT.T_BOARD (ARTICLENO,PARENTNO,TITLE,CONTENT,IMAGEFILENAME,WRITEDATE,ID,SORT,CNT) values (6,2,'상품후기입니다','이순신씨의 상품 사용 후기를 올립니다!!',null,to_date('23/02/05 16:28:05','RR/MM/DD HH24:MI:SS'),'lee',1,1);
Insert into C##SCOTT.T_BOARD (ARTICLENO,PARENTNO,TITLE,CONTENT,IMAGEFILENAME,WRITEDATE,ID,SORT,CNT) values (10,0,'fdfd','fdfdf','다운로드.jpg',to_date('23/02/09 15:51:19','RR/MM/DD HH24:MI:SS'),'hong',1,3);
Insert into C##SCOTT.T_BOARD (ARTICLENO,PARENTNO,TITLE,CONTENT,IMAGEFILENAME,WRITEDATE,ID,SORT,CNT) values (11,0,'0216 일반','일반글 ',null,to_date('23/02/16 15:40:56','RR/MM/DD HH24:MI:SS'),'hong',1,2);
--------------------------------------------------------
--  DDL for Index SYS_C008367
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."SYS_C008367" ON "C##SCOTT"."T_BOARD" ("ARTICLENO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table T_BOARD
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."T_BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."T_BOARD" MODIFY ("WRITEDATE" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."T_BOARD" ADD PRIMARY KEY ("ARTICLENO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_BOARD
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."T_BOARD" ADD CONSTRAINT "FK_ID" FOREIGN KEY ("ID")
	  REFERENCES "C##SCOTT"."T_MEMBER" ("ID") ENABLE;
