--------------------------------------------------------
--  파일이 생성됨 - 월요일-2월-27-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_SHOPPING_GOODS
--------------------------------------------------------

  CREATE TABLE "SCOTT"."T_SHOPPING_GOODS" 
   (	"GOODS_ID" NUMBER(20,0), 
	"GOODS_SORT" VARCHAR2(50 BYTE), 
	"GOODS_TITLE" VARCHAR2(100 BYTE), 
	"GOODS_WRITER" VARCHAR2(50 BYTE), 
	"GOODS_PUBLISHER" VARCHAR2(50 BYTE), 
	"GOODS_PRICE" NUMBER(10,0), 
	"GOODS_SALES_PRICE" NUMBER(10,0), 
	"GOODS_POINT" NUMBER(10,0), 
	"GOODS_PUBLISHED_DATE" DATE, 
	"GOODS_TOTAL_PAGE" NUMBER(5,0), 
	"GOODS_ISBN" VARCHAR2(50 BYTE), 
	"GOODS_DELIVERY_PRICE" NUMBER(10,0), 
	"GOODS_DELIVERY_DATE" DATE, 
	"GOODS_STATUS" VARCHAR2(50 BYTE), 
	"GOODS_INTRO" VARCHAR2(2000 BYTE), 
	"GOODS_WRITER_INTRO" VARCHAR2(2000 BYTE), 
	"GOODS_PUBLISHER_COMMENT" VARCHAR2(2000 BYTE), 
	"GOODS_RECOMMENDATION" VARCHAR2(2000 BYTE), 
	"GOODS_CONTENTS_ORDER" CLOB, 
	"GOODS_CREDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("GOODS_CONTENTS_ORDER") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into SCOTT.T_SHOPPING_GOODS
SET DEFINE OFF;
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (398,'리시안셔스','리시안셔스 로베라핑크','admin','admin',30000,27000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'bestseller','핑크빛이 도는 리시안셔스','핑크빛이 도는 리시안셔스','핑크빛이 도는 리시안셔스','핑크빛이 도는 리시안셔스',to_date('23/02/27','RR/MM/DD'));
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (334,'리시안셔스','리시안셔스 핑크','admin','admin',30000,27000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'steadyseller','화사한 핑크빛의 리시안셔스','화사한 핑크빛의 리시안셔스','화사한 핑크빛의 리시안셔스','화사한 핑크빛의 리시안셔스',to_date('23/02/27','RR/MM/DD'));
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (335,'미니거베라','미니거베라 코랄핑크','admin','admin',29000,25000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'newbook','거베라는 다른 꽃들과는 다른 재미있는 꽃말을 가지고 있어요. 신비, 수수께끼, 계속 궁금해 지는 신비로운 상대방에게 꽃말마저 매력적인 거베라를 안겨 주세요.','거베라는 다른 꽃들과는 다른 재미있는 꽃말을 가지고 있어요. 신비, 수수께끼, 계속 궁금해 지는 신비로운 상대방에게 꽃말마저 매력적인 거베라를 안겨 주세요.','거베라는 다른 꽃들과는 다른 재미있는 꽃말을 가지고 있어요. 신비, 수수께끼, 계속 궁금해 지는 신비로운 상대방에게 꽃말마저 매력적인 거베라를 안겨 주세요.','거베라는 다른 꽃들과는 다른 재미있는 꽃말을 가지고 있어요. 신비, 수수께끼, 계속 궁금해 지는 신비로운 상대방에게 꽃말마저 매력적인 거베라를 안겨 주세요.',to_date('23/02/27','RR/MM/DD'));
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (336,'미니델피늄','미니델피늄 연블루','admin','admin',29000,25000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'bestseller','당신은 왜 저를 미워하나요,경솔, 자유, 깊이 생각치 않고 자유롭게 살아가는 것이 숙명','당신은 왜 저를 미워하나요,경솔, 자유, 깊이 생각치 않고 자유롭게 살아가는 것이 숙명','당신은 왜 저를 미워하나요,경솔, 자유, 깊이 생각치 않고 자유롭게 살아가는 것이 숙명','당신은 왜 저를 미워하나요,경솔, 자유, 깊이 생각치 않고 자유롭게 살아가는 것이 숙명',to_date('23/02/27','RR/MM/DD'));
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (337,'버터플라이','버터플라이 옐로우','admin','admin',30000,27000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'bestseller','매력, 매혹 그리고 비난..','매력, 매혹 그리고 비난..','매력, 매혹 그리고 비난..','매력, 매혹 그리고 비난..',to_date('23/02/27','RR/MM/DD'));
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (338,'버터플라이 ','버터플라이 진핑크','admin','admin',33000,28000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'bestseller','매력, 매혹 그리고 비난..','매력, 매혹 그리고 비난..','매력, 매혹 그리고 비난..','매력, 매혹 그리고 비난..',to_date('23/02/27','RR/MM/DD'));
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (339,'수국','수국 핑크','admin','admin',33000,28000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'steadyseller','수국의 꽃말은 변덕, 변심과 같은 의미를 지니고 있기도 합니다..','수국의 꽃말은 변덕, 변심과 같은 의미를 지니고 있기도 합니다..','수국의 꽃말은 변덕, 변심과 같은 의미를 지니고 있기도 합니다..','수국의 꽃말은 변덕, 변심과 같은 의미를 지니고 있기도 합니다..',to_date('23/02/27','RR/MM/DD'));
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (340,'심비디움','심비디움 핑크','admin','admin',30000,27000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'steadyseller','심비디움은 신분이 높거나 재산이 많은 집안의 부인을 뜻하는 귀부인이라는 꽃말을 가지고 있습니다','심비디움은 신분이 높거나 재산이 많은 집안의 부인을 뜻하는 귀부인이라는 꽃말을 가지고 있습니다','심비디움은 신분이 높거나 재산이 많은 집안의 부인을 뜻하는 귀부인이라는 꽃말을 가지고 있습니다','심비디움은 신분이 높거나 재산이 많은 집안의 부인을 뜻하는 귀부인이라는 꽃말을 가지고 있습니다',to_date('23/02/27','RR/MM/DD'));
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (341,'아시틸베','아시틸베 화이트','admin','admin',30000,27000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'steadyseller','나는 여전히 당신을 기다립니다 라는 애타는 뜻으로, 기약 없는 사랑을 의미합니다.','나는 여전히 당신을 기다립니다 라는 애타는 뜻으로, 기약 없는 사랑을 의미합니다.','나는 여전히 당신을 기다립니다 라는 애타는 뜻으로, 기약 없는 사랑을 의미합니다.','나는 여전히 당신을 기다립니다 라는 애타는 뜻으로, 기약 없는 사랑을 의미합니다.',to_date('23/02/27','RR/MM/DD'));
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (342,'장미','장미 레인댄스','admin','admin',24000,20000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'newbook','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.',to_date('23/02/27','RR/MM/DD'));
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (343,'장미','장미 비소우','admin','admin',27000,24000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'newbook','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.',to_date('23/02/27','RR/MM/DD'));
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (344,'장미','장미 부르트','admin','admin',22000,19000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'newbook','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.',to_date('23/02/27','RR/MM/DD'));
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (345,'장미','장미 도미니카','admin','admin',30000,27000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'bestseller','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.',to_date('23/02/27','RR/MM/DD'));
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (346,'장미','장미 레드미니','admin','admin',30000,27000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'steadyseller','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.','장미의 색상,갯수 마다 꽃말이 다릅니다.',to_date('23/02/27','RR/MM/DD'));
Insert into SCOTT.T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (347,'시레네','시레네','admin','admin',32000,26000,1000,to_date('23/02/27','RR/MM/DD'),1000,'121212',2000,to_date('23/02/27','RR/MM/DD'),'newbook','시레네 · 카로리니아나 꽃말은 미련..','시레네 · 카로리니아나 꽃말은 미련..','시레네 · 카로리니아나 꽃말은 미련..','시레네 · 카로리니아나 꽃말은 미련..',to_date('23/02/27','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007231
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C007231" ON "SCOTT"."T_SHOPPING_GOODS" ("GOODS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table T_SHOPPING_GOODS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."T_SHOPPING_GOODS" ADD PRIMARY KEY ("GOODS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
